/* start på punktion. kalder samtidig de forskellige elementer */
$(window).scroll(function () {

    var scrollPosition = $(this).scrollTop();
    var halfWindowheight = $(window).height() / 2;
    var page1Top = 0;
    var page2Top = $('.page2').offset().top - halfWindowheight;
    var page3Top = $('.page3').offset().top - halfWindowheight;
    var page4Top = $('.page4').offset().top - halfWindowheight;
    var page6Top = $('.page6').offset().top - halfWindowheight;
    var page7Top = $('.page7').offset().top - halfWindowheight;
    var page8Top = $('.page8').offset().top - halfWindowheight;
    var page9Top = $('.page9').offset().top - halfWindowheight;

    /* sektionen herunder fortæller hvornår de forskellige kort skal bevæge sig på siden */
    if (scrollPosition > page1Top && scrollPosition < page2Top) {
        $('.page1-title').addClass('page1-title-active');
        $('.page1-desc').addClass('page1-desc-active');
        $('.saks').addClass('saks-active');
        $('.pg2-white-desc').removeClass('pg2-white-desc-active');
        $('.pg2-photo-wrap').removeClass('pg2-photo-wrap-active');
        $('.pg2-photo').removeClass('pg2-photo-active');
        $('.pg3-white-desc').removeClass('pg3-white-desc-active');
        $('.pg3-photo-wrap').removeClass('pg3-photo-wrap-active');
        $('.pg3-photo').removeClass('pg3-photo-active');
        $('.pg4-white-desc').removeClass('pg4-white-desc-active');
        $('.pg4-photo-wrap').removeClass('pg4-photo-wrap-active');
        $('.pg4-photo').removeClass('pg4-photo-active');
        $('.pg6-white-desc').removeClass('pg6-white-desc-active');
        $('.pg6-photo-wrap').removeClass('pg6-photo-wrap-active');
        $('.pg6-photo').removeClass('pg6-photo-active');
        $('.pg7-white-desc').removeClass('pg7-white-desc-active');
        $('.pg7-photo-wrap').removeClass('pg7-photo-wrap-active');
        $('.pg7-photo').removeClass('pg7-photo-active');
        $('.pg8-white-desc').removeClass('pg8-white-desc-active');
        $('.pg8-photo-wrap').removeClass('pg8-photo-wrap-active');
        $('.pg8-photo').removeClass('pg8-photo-active');
        $('.pg9-white-desc').removeClass('pg9-white-desc-active');
        $('.pg9-photo-wrap').removeClass('pg9-photo-wrap-active');
        $('.pg9-photo').removeClass('pg9-photo-active');
    } else if (scrollPosition > page2Top && scrollPosition < page3Top) {
        $('.body-wrap').removeClass('body-wrap-active');
        $('.page1-title').removeClass('page1-title-active');
        $('.page1-desc').removeClass('page1-desc-active');
        $('.saks').removeClass('saks-active');
        $('.pg2-white-desc').addClass('pg2-white-desc-active');
        $('.pg2-photo-wrap').addClass('pg2-photo-wrap-active');
        $('.pg2-photo').addClass('pg2-photo-active');
        $('.pg3-white-desc').removeClass('pg3-white-desc-active');
        $('.pg3-photo-wrap').removeClass('pg3-photo-wrap-active');
        $('.pg3-photo').removeClass('pg3-photo-active');
        $('.pg4-white-desc').removeClass('pg4-white-desc-active');
        $('.pg4-photo-wrap').removeClass('pg4-photo-wrap-active');
        $('.pg4-photo').removeClass('pg4-photo-active');
        $('.pg6-white-desc').removeClass('pg6-white-desc-active');
        $('.pg6-photo-wrap').removeClass('pg6-photo-wrap-active');
        $('.pg6-photo').removeClass('pg6-photo-active');
        $('.pg7-white-desc').removeClass('pg7-white-desc-active');
        $('.pg7-photo-wrap').removeClass('pg7-photo-wrap-active');
        $('.pg7-photo').removeClass('pg7-photo-active');
        $('.pg8-white-desc').removeClass('pg8-white-desc-active');
        $('.pg8-photo-wrap').removeClass('pg8-photo-wrap-active');
        $('.pg8-photo').removeClass('pg8-photo-active');
        $('.pg9-white-desc').removeClass('pg9-white-desc-active');
        $('.pg9-photo-wrap').removeClass('pg9-photo-wrap-active');
        $('.pg9-photo').removeClass('pg9-photo-active');
    } else if (scrollPosition > page3Top && scrollPosition < page4Top) {
        $('.page1-title').removeClass('page1-title-active');
        $('.page1-desc').removeClass('page1-desc-active');
        $('.saks').removeClass('saks-active');
        $('.pg2-white-desc').removeClass('pg2-white-desc-active');
        $('.pg2-photo-wrap').removeClass('pg2-photo-wrap-active');
        $('.pg2-photo').removeClass('pg2-photo-active');
        $('.pg3-white-desc').addClass('pg3-white-desc-active');
        $('.pg3-photo-wrap').addClass('pg3-photo-wrap-active');
        $('.pg3-photo').addClass('pg3-photo-active');
        $('.pg4-white-desc').removeClass('pg4-white-desc-active');
        $('.pg4-photo-wrap').removeClass('pg4-photo-wrap-active');
        $('.pg4-photo').removeClass('pg4-photo-active');
        $('.pg6-white-desc').removeClass('pg6-white-desc-active');
        $('.pg6-photo-wrap').removeClass('pg6-photo-wrap-active');
        $('.pg6-photo').removeClass('pg6-photo-active');
        $('.pg7-white-desc').removeClass('pg7-white-desc-active');
        $('.pg7-photo-wrap').removeClass('pg7-photo-wrap-active');
        $('.pg7-photo').removeClass('pg7-photo-active');
        $('.pg8-white-desc').removeClass('pg8-white-desc-active');
        $('.pg8-photo-wrap').removeClass('pg8-photo-wrap-active');
        $('.pg8-photo').removeClass('pg8-photo-active');
        $('.pg9-white-desc').removeClass('pg9-white-desc-active');
        $('.pg9-photo-wrap').removeClass('pg9-photo-wrap-active');
        $('.pg9-photo').removeClass('pg9-photo-active');
    } else if (scrollPosition > page4Top && scrollPosition < page6Top) {
        $('.page1-title').removeClass('page1-title-active');
        $('.page1-desc').removeClass('page1-desc-active');
        $('.saks').removeClass('saks-active');
        $('.pg2-white-desc').removeClass('pg2-white-desc-active');
        $('.pg2-photo-wrap').removeClass('pg2-photo-wrap-active');
        $('.pg2-photo').removeClass('pg2-photo-active');
        $('.pg3-white-desc').removeClass('pg3-white-desc-active');
        $('.pg3-photo-wrap').removeClass('pg3-photo-wrap-active');
        $('.pg3-photo').removeClass('pg3-photo-active');
        $('.pg4-white-desc').addClass('pg4-white-desc-active');
        $('.pg4-photo-wrap').addClass('pg4-photo-wrap-active');
        $('.pg4-photo').addClass('pg4-photo-active');
        $('.pg6-white-desc').removeClass('pg6-white-desc-active');
        $('.pg6-photo-wrap').removeClass('pg6-photo-wrap-active');
        $('.pg6-photo').removeClass('pg6-photo-active');
        $('.pg7-white-desc').removeClass('pg7-white-desc-active');
        $('.pg7-photo-wrap').removeClass('pg7-photo-wrap-active');
        $('.pg7-photo').removeClass('pg7-photo-active');
        $('.pg8-white-desc').removeClass('pg8-white-desc-active');
        $('.pg8-photo-wrap').removeClass('pg8-photo-wrap-active');
        $('.pg8-photo').removeClass('pg8-photo-active');
        $('.pg9-white-desc').removeClass('pg9-white-desc-active');
        $('.pg9-photo-wrap').removeClass('pg9-photo-wrap-active');
        $('.pg9-photo').removeClass('pg9-photo-active');
    } else if (scrollPosition > page6Top && scrollPosition < page7Top) {
        $('.page1-title').removeClass('page1-title-active');
        $('.page1-desc').removeClass('page1-desc-active');
        $('.saks').removeClass('saks-active');
        $('.pg2-white-desc').removeClass('pg2-white-desc-active');
        $('.pg2-photo-wrap').removeClass('pg2-photo-wrap-active');
        $('.pg2-photo').removeClass('pg2-photo-active');
        $('.pg3-white-desc').removeClass('pg3-white-desc-active');
        $('.pg3-photo-wrap').removeClass('pg3-photo-wrap-active');
        $('.pg3-photo').removeClass('pg3-photo-active');
        $('.pg4-white-desc').removeClass('pg4-white-desc-active');
        $('.pg4-photo-wrap').removeClass('pg4-photo-wrap-active');
        $('.pg4-photo').removeClass('pg4-photo-active');
        $('.pg6-white-desc').addClass('pg6-white-desc-active');
        $('.pg6-photo-wrap').addClass('pg6-photo-wrap-active');
        $('.pg6-photo').addClass('pg6-photo-active');
        $('.pg7-white-desc').removeClass('pg7-white-desc-active');
        $('.pg7-photo-wrap').removeClass('pg7-photo-wrap-active');
        $('.pg7-photo').removeClass('pg7-photo-active');
        $('.pg8-white-desc').removeClass('pg8-white-desc-active');
        $('.pg8-photo-wrap').removeClass('pg8-photo-wrap-active');
        $('.pg8-photo').removeClass('pg8-photo-active');
        $('.pg9-white-desc').removeClass('pg9-white-desc-active');
        $('.pg9-photo-wrap').removeClass('pg9-photo-wrap-active');
        $('.pg9-photo').removeClass('pg9-photo-active');
    } else if (scrollPosition > page7Top && scrollPosition < page8Top) {
        $('.page1-title').removeClass('page1-title-active');
        $('.page1-desc').removeClass('page1-desc-active');
        $('.saks').removeClass('saks-active');
        $('.pg2-white-desc').removeClass('pg2-white-desc-active');
        $('.pg2-photo-wrap').removeClass('pg2-photo-wrap-active');
        $('.pg2-photo').removeClass('pg2-photo-active');
        $('.pg3-white-desc').removeClass('pg3-white-desc-active');
        $('.pg3-photo-wrap').removeClass('pg3-photo-wrap-active');
        $('.pg3-photo').removeClass('pg3-photo-active');
        $('.pg4-white-desc').removeClass('pg4-white-desc-active');
        $('.pg4-photo-wrap').removeClass('pg4-photo-wrap-active');
        $('.pg4-photo').removeClass('pg4-photo-active');
        $('.pg6-white-desc').removeClass('pg6-white-desc-active');
        $('.pg6-photo-wrap').removeClass('pg6-photo-wrap-active');
        $('.pg6-photo').removeClass('pg6-photo-active');
        $('.pg7-white-desc').addClass('pg7-white-desc-active');
        $('.pg7-photo-wrap').addClass('pg7-photo-wrap-active');
        $('.pg7-photo').addClass('pg7-photo-active');
        $('.pg8-white-desc').removeClass('pg8-white-desc-active');
        $('.pg8-photo-wrap').removeClass('pg8-photo-wrap-active');
        $('.pg8-photo').removeClass('pg8-photo-active');
        $('.pg9-white-desc').removeClass('pg9-white-desc-active');
        $('.pg9-photo-wrap').removeClass('pg9-photo-wrap-active');
        $('.pg9-photo').removeClass('pg9-photo-active');
    } else if (scrollPosition > page8Top && scrollPosition < page9Top) {
        $('.page1-title').removeClass('page1-title-active');
        $('.page1-desc').removeClass('page1-desc-active');
        $('.saks').removeClass('saks-active');
        $('.pg2-white-desc').removeClass('pg2-white-desc-active');
        $('.pg2-photo-wrap').removeClass('pg2-photo-wrap-active');
        $('.pg2-photo').removeClass('pg2-photo-active');
        $('.pg3-white-desc').removeClass('pg3-white-desc-active');
        $('.pg3-photo-wrap').removeClass('pg3-photo-wrap-active');
        $('.pg3-photo').removeClass('pg3-photo-active');
        $('.pg4-white-desc').removeClass('pg4-white-desc-active');
        $('.pg4-photo-wrap').removeClass('pg4-photo-wrap-active');
        $('.pg4-photo').removeClass('pg4-photo-active');
        $('.pg6-white-desc').removeClass('pg6-white-desc-active');
        $('.pg6-photo-wrap').removeClass('pg6-photo-wrap-active');
        $('.pg6-photo').removeClass('pg6-photo-active');
        $('.pg7-white-desc').removeClass('pg7-white-desc-active');
        $('.pg7-photo-wrap').removeClass('pg7-photo-wrap-active');
        $('.pg7-photo').removeClass('pg7-photo-active');
        $('.pg8-white-desc').addClass('pg8-white-desc-active');
        $('.pg8-photo-wrap').addClass('pg8-photo-wrap-active');
        $('.pg8-photo').addClass('pg8-photo-active');
        $('.pg9-white-desc').removeClass('pg9-white-desc-active');
        $('.pg9-photo-wrap').removeClass('pg9-photo-wrap-active');
        $('.pg9-photo').removeClass('pg9-photo-active');
    } else if (scrollPosition > page9Top) {
        $('.page1-title').removeClass('page1-title-active');
        $('.page1-desc').removeClass('page1-desc-active');
        $('.saks').removeClass('saks-active');
        $('.pg2-white-desc').removeClass('pg2-white-desc-active');
        $('.pg2-photo-wrap').removeClass('pg2-photo-wrap-active');
        $('.pg2-photo').removeClass('pg2-photo-active');
        $('.pg3-white-desc').removeClass('pg3-white-desc-active');
        $('.pg3-photo-wrap').removeClass('pg3-photo-wrap-active');
        $('.pg3-photo').removeClass('pg3-photo-active');
        $('.pg4-white-desc').removeClass('pg4-white-desc-active');
        $('.pg4-photo-wrap').removeClass('pg4-photo-wrap-active');
        $('.pg4-photo').removeClass('pg4-photo-active');
        $('.pg6-white-desc').removeClass('pg6-white-desc-active');
        $('.pg6-photo-wrap').removeClass('pg6-photo-wrap-active');
        $('.pg6-photo').removeClass('pg6-photo-active');
        $('.pg7-white-desc').removeClass('pg7-white-desc-active');
        $('.pg7-photo-wrap').removeClass('pg7-photo-wrap-active');
        $('.pg7-photo').removeClass('pg7-photo-active');
        $('.pg8-white-desc').removeClass('pg8-white-desc-active');
        $('.pg8-photo-wrap').removeClass('pg8-photo-wrap-active');
        $('.pg8-photo').removeClass('pg8-photo-active');
        $('.pg9-white-desc').addClass('pg9-white-desc-active');
        $('.pg9-photo-wrap').addClass('pg9-photo-wrap-active');
        $('.pg9-photo').addClass('pg9-photo-active');
    };
});
